README.md
Please review membership settings for this chat room.
=> This is an "invite only" channel.

CHANGELOG.md
ELSA-2024-0627/CVE-2024-0553
ELSA-2024-0628/CVE-2023-48795
ELSA-2024-0647/CVE-2021-35937/CVE-2021-35938/CVE-2021-35939 ELSA-2024-0533/CVE-2023-5981/CVE-2024-0553/CVE-2024-0567
=> Updated change log for:

CHANGELOG.md
ELSA-2024-1879/CVE-2024-28834/CVE-2024-28835
=> Updated change log for ELSA-2024-1879/CVE-2024-28834/CVE-2024-28835

CHANGELOG.md
=> Updated change log for OL8 container update for ELSA-2024-3626/CVE-2024-25062

CHANGELOG.md
=> Updated changelog for ELSA-2024-3501/CVE-2024-28182

CHANGELOG.md
ELSA-2024-4078/CVE-2023-6597/CVE-2024-0450
=> Updated changelog for ELSA-2024-4078/CVE-2023-6597/CVE-2024-0450

CHANGELOG.md
=> Updated changelog for ELSA-2024-4457/CVE-2024-6409

CHANGELOG.md
=> Updated changelog for ELSA-2024-4779/CVE-2024-4032

CHANGELOG.md
ELSA-2024-5312/CVE-2024-37370/CVE-2024-37371
=> Updated changelog for ELSA-2024-5312/CVE-2024-37370/CVE-2024-37371

CHANGELOG.md
ELBA-2024-5691
ELBA-2024-5736
ELSA-2024-5654
=> Updated changelog for ELSA-2024-5654 ELBA-2024-5691 ELBA-2024-5736

CHANGELOG.md
=> Updated changelog for ELSA-2024-6464/CVE-2024-34397

CHANGELOG.md
=> Updated changelog for ELSA-2024-7848/CVE-2024-5535

CHANGELOG.md
=> Updated changelog for ELBA-2024-8805 tzdata 2024b

CHANGELOG.md
ELSA-2024-8922/CVE-2019-12900
ELSA-2024-8860/CVE-2024-3596
ELBA-2024-8805/tzdata-2024b
=> Updated changelog for ELSA-2024-8922/CVE-2019-12900 ELSA-2024-8860/CVE-2024-3596 ELBA-2024-8805

CHANGELOG.md
=> Updated changelog for 

CHANGELOG.md
ELSA-2024-10244/CVE-2024-10963
=> Updated changelog for ELSA-2024-10244/CVE-2024-10963

CHANGELOG.md
ELSA-2024-10379/CVE-2024-10041/CVE-2024-10963
=> Updated changelog for ELSA-2024-10379/CVE-2024-10041/CVE-2024-10963

CHANGELOG.md
ELSA-2024-10779/CVE-2024-11168/CVE-2024-9287
=> Updated changelog for ELSA-2024-10779/CVE-2024-11168/CVE-2024-9287

CHANGELOG.md
=> Updated changelog for ELSA-2024-8788/CVE-2024-3596

CHANGELOG.md
ELSA-2024-10983/CVE-2024-11168/CVE-2024-9287
=> Updated changelog for ELSA-2024-10983/CVE-2024-11168/CVE-2024-9287

CHANGELOG.md
ELSA-2024-11250/CVE-2024-10041
=> Updated changelog for ELSA-2024-11250/CVE-2024-10041

CHANGELOG.md
=> Updated changelog for ELSA-2025-0733/CVE-2019-12900

CHANGELOG.md
=> Updated changelog for ELSA-2025-1675/CVE-2024-11187

CHANGELOG.md
ELSA-2025-2679/CVE-2024-56171/CVE-2025-24928
=> Updated changelog for ELSA-2025-2679/CVE-2024-56171/CVE-2025-24928

CHANGELOG.md
=> Updated changelog for tzdata-2025b.

CHANGELOG.md
=> Updated changelog for ELSA-2025-3531/CVE-2024-8176

CHANGELOG.md
=> Updated changelog for ELSA-2025-3828/CVE-2025-0395

CHANGELOG.md
=> Updated changelog for ELSA-2025-3913/CVE-2024-8176

CHANGELOG.md
=> Updated changelog for ELSA-2025-4244/CVE-2025-0395

CHANGELOG.md
=> Updated changelog for ELSA-2025-10027/CVE-2025-6020

CHANGELOG.md
ELSA-2025-10136/CVE-2024-12718/CVE-2025-4138/CVE-2025-4330/CVE-2025-4435/CVE-2025-4517
=> Updated changelog for ELSA-2025-10136/CVE-2024-12718/CVE-2025-4138/CVE-2025-4330/CVE-2025-4435/CVE-2025-4517

CHANGELOG.md
ELSA-2025-7512/CVE-2024-8176
ELSA-2025-9421/CVE-2025-47268
ELSA-2025-9418/CVE-2025-3576
ELSA-2025-7510/CVE-2024-57970
ELSA-2025-9420/CVE-2025-25724
ELSA-2025-10630/CVE-2025-49794/CVE-2025-49795/CVE-2025-49796/CVE-2025-6021
ELSA-2025-9940/CVE-2025-47273
ELSA-2025-7517/CVE-2025-3277
ELEA-2025-7514/tzdata
ELSA-2025-7524/CVE-2025-31115
ELSA-2025-10407/CVE-2025-47273
=> Multiple OL10 errata and an OL9 erratum

CHANGELOG.md
ELSA-2025-10699/CVE-2025-49794/CVE-2025-49796/CVE-2025-6021
=> Updated changelog for ELSA-2025-10699/CVE-2025-49794/CVE-2025-49796/CVE-2025-6021

CHANGELOG.md
ELSA-2025-11140/CVE-2024-52533/CVE-2025-4373
ELSA-2025-11035/CVE-2019-17543
ELSA-2025-11036/CVE-2025-47273
=> Updated changelog for ELSA-2025-11140/CVE-2024-52533/CVE-2025-4373/ELSA-2025-11035/CVE-2019-17543/ELSA-2025-11036/CVE-2025-47273

CHANGELOG.md
ELSA-2025-11327/CVE-2024-34397/CVE-2024-52533/CVE-2025-4373
=> Updated changelog for ELSA-2025-11327/CVE-2024-34397/CVE-2024-52533/CVE-2025-4373

CHANGELOG.md
ELSA-2025-16823/CVE-2025-26465
=> Updated changelog for ELSA-2025-16823/CVE-2025-26465
